### ISSUE TITLE
4 tests fails by jdk main-line repo

### ISSUE THREAD

**Issue by sendaoYan** [rh-openjdk/CryptoTest#74]
Follow 4 tests fails run with main-line repo build jdk

```
cryptotest/tests/KEMTests.java
cryptotest/tests/KeyFactoryTests.java
cryptotest/tests/KeyPairGeneratorTests.java
cryptotest/tests/SignatureTests.java
```

Test log snippet:
```
** failed runs: 10 **
java.lang.Exception: 0)	SunJCE: 	ML-KEM-1024~ML-KEM-1024	 (KEM)
	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:102)
	at cryptotest.tests.KEMTests.main(KEMTests.java:62)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: cryptotest.utils.AlgorithmRunException: java.lang.RuntimeException: Unsupported KEM algorithm: ML-KEM-1024
	at cryptotest.tests.KEMTests.checkAlgorithm(KEMTests.java:137)
	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:96)
	... 5 more
Caused by: java.lang.RuntimeException: Unsupported KEM algorithm: ML-KEM-1024
	at cryptotest.tests.KEMTests.checkAlgorithm(KEMTests.java:118)
	... 6 more
```

The full log:
[cryptotest.log](https://github.com/user-attachments/files/17878180/cryptotest.log)

**Comment by judovana** [comment]
Thanx! It looks like jdk24 will be heavy one for this suite.
